# Generated by Django 3.1.7 on 2021-05-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='customer',
            new_name='userprofile',
        ),
    ]
